steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '.'

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/commonly-493005/docker/commonly-backend:latest'
