steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_REACT_APP_API_URL}'
      - '--build-arg'
      - 'REACT_APP_API_URL=${_REACT_APP_API_URL}'
      - '-t'
      - '${_IMAGE}'
      - '.'

images:
  - '${_IMAGE}'

substitutions:
  _REACT_APP_API_URL: 'https://api-dev.commonly.me'
  _IMAGE: 'us-central1-docker.pkg.dev/commonly-493005/docker/commonly-frontend:latest'
