{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "commonly.namespace" . }}
  labels:
    {{- include "commonly.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "commonly.redis.selectorLabels" . | nindent 4 }}
{{- end }}
