{{- if or .Values.backup.mongodb.enabled .Values.backup.postgresql.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: {{ include "commonly.namespace" . }}
  labels:
    {{- include "commonly.labels" . | nindent 4 }}
    component: backup
  {{- with .Values.backup.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ . | quote }}
  {{- end }}
{{- end }}
