{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ include "commonly.namespace" . }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectId | quote }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
{{- end }}
