{{- if .Values.externalSecrets.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccount.name }}
  namespace: {{ include "commonly.namespace" . }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.externalSecrets.serviceAccount.gcpServiceAccount }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ include "commonly.namespace" . }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.secretStore.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.secretStore.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccount.name }}
{{- end }}
